# Generated by Django 5.0.4 on 2024-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
